Fixing fuzz build errors
My previous commit was only about updating links in documentation .md file.
But the fuzzing build broke with:
```
'default_options_guard.h' file not found
```
Didn't expect that with a no code change. But I have dealt with the same issue
on commit 5fc636979d25d26612f0453916a13b232af574cf. From my localtesting I figured
this is a race condition when running make with parallel jobs. I could only
reproduce the problem with `make -j4`. I also didn't hit the problem earlier or
more regularly, because `make clean` doesn't remove `default_options_guard.h`, so
for subsequent runs that dependency is already satisfied, and there's no job
racing to complete it.

Hopefully this would work on the GitHub pipeline as well as on my local machine. The
uncertainty is the support for the special `.NOTPARALLEL` target by the make
implementation on the pipeline.

Before this change:
```
make -j4 fuzzstandalone
Creating default_options_guard.h
gcc -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT  -c -o fuzz/fuzz-common.o fuzz/fuzz-common.c
gcc -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT  -c -o fuzz/fuzz-wrapfd.o fuzz/fuzz-wrapfd.c
gcc -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT  -c -o fuzz/fuzzer-preauth.o fuzz/fuzzer-preauth.c
In file included from ./src/includes.h:28,
                 from fuzz/fuzz-common.c:3:
./src/options.h:20:10: fatal error: default_options_guard.h: No such file or directory
   20 | #include "default_options_guard.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./src/includes.h:28,
                 from fuzz/fuzz-wrapfd.c:2:
./src/options.h:20:10: fatal error: default_options_guard.h: No such file or directory
   20 | #include "default_options_guard.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

```
make -j4 fuzz-targets FUZZLIB=-lFuzzer.a
Creating default_options_guard.h
gcc -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT  -c -o fuzz/fuzz-common.o fuzz/fuzz-common.c
gcc -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT  -c -o fuzz/fuzz-wrapfd.o fuzz/fuzz-wrapfd.c
gcc -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT  -c -o fuzz/fuzzer-preauth.o fuzz/fuzzer-preauth.c
In file included from ./src/includes.h:28,
                 from fuzz/fuzz-wrapfd.c:2:
./src/options.h:20:10: fatal error: default_options_guard.h: No such file or directory
   20 | #include "default_options_guard.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./src/includes.h:28,
                 from fuzz/fuzz-common.c:3:
./src/options.h:20:10: fatal error: default_options_guard.h: No such file or directory
   20 | #include "default_options_guard.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

The above clearly shows multiple jobs running, and some do before `default_options_guard.h` is available.

After this change:
```
make -j4 fuzzstandalone
Creating default_options_guard.h
/home/tjkolev/dev/dropbear
-rw-rw-r-- 1 tjkolev tjkolev 17419 Mar 13 09:54 default_options_guard.h
make -C libtomcrypt
make[1]: Entering directory '/home/tjkolev/dev/dropbear/libtomcrypt'
gcc -Isrc/headers/ -I./src/headers/ -I./.. -I./../src -DLTC_SOURCE -I../libtommath/ -I./../libtommath/ -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT -c src/ciphers/aes/aes.c -o src/ciphers/aes/aes.o
```

```
make -j4 fuzz-targets FUZZLIB=-lFuzzer.a
Creating default_options_guard.h
/home/tjkolev/dev/dropbear
-rw-rw-r-- 1 tjkolev tjkolev 17419 Mar 13 09:54 default_options_guard.h
make -C libtomcrypt
make[1]: Entering directory '/home/tjkolev/dev/dropbear/libtomcrypt'
gcc -Isrc/headers/ -I./src/headers/ -I./.. -I./../src -DLTC_SOURCE -I../libtommath/ -I./../libtommath/ -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -Os -W -Wall -I./libtomcrypt/src/headers/ -I./libtommath -DLOCALOPTIONS_H_EXISTS -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT -c src/ciphers/aes/aes.c -o src/ciphers/aes/aes.o
```

`default_options_guard.h` gets created before any other make jobs start working.

tjk :)