Revert "ci: build scp"
PROGRESS_METER conditional causes
    error: variable 'statbytes' set but not used

This reverts commit de87f98c0e15fb6ab897566f77acce1778d613a5.